// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'path': string;
  'reason': string;
  'row': string;
  'selectedContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
