// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'canonicalAuthorFolderInput': string;
  'canonicalAuthorFolderInputContainer': string;
  'canonicalAuthorFolderLabel': string;
  'canonicalAuthorFolderOption': string;
  'path': string;
  'previews': string;
  'selectAllInput': string;
  'selectAllInputContainer': string;
  'trackFormat': string;
}
export const cssExports: CssExports;
export default cssExports;
